"""add_native_auth_and_user_profile_columns

Revision ID: 4f863e33cd00
Revises: a2b3c4d5e6f7
Create Date: 2026-09-29 03:56:02.342270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f863e33cd00'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('monthly_capacity', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'monthly_capacity')
    op.drop_column('users', 'monthly_income')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
