"""create_initial_schema

Revision ID: f1ac52790be1
Revises: 
Create Date: 2026-09-28 12:44:12.084519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ac52790be1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_auth_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_auth_id'), 'users', ['external_auth_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('attachment_reference', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Identity', 'Financial', 'Medical', 'Insurance', 'Education', 'Property', 'Vehicle', 'Other')", name='ck_document_category_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_user_expiry_date', 'documents', ['user_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Food & Dining', 'Transport', 'Shopping', 'Bills & Utilities', 'Other')", name='ck_expense_category_valid'),
    sa.CheckConstraint('amount > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_user_transaction_date', 'expenses', ['user_id', 'transaction_date'], unique=False)
    op.create_table('financial_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High')", name='ck_financial_goal_priority_valid'),
    sa.CheckConstraint('current_amount >= 0', name='ck_financial_goal_current_amount_non_negative'),
    sa.CheckConstraint('monthly_contribution >= 0', name='ck_financial_goal_monthly_contribution_non_negative'),
    sa.CheckConstraint('target_amount >= 0', name='ck_financial_goal_target_amount_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_goals_user_id', 'financial_goals', ['user_id'], unique=False)
    op.create_table('goal_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('base_plan_reference', sa.String(length=255), nullable=True),
    sa.Column('scenario_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feasibility_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_scenarios_user_id', 'goal_scenarios', ['user_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.Column('installments_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('installments_paid <= total_installments', name='ck_investment_installments_paid_lte_total'),
    sa.CheckConstraint('installments_paid >= 0', name='ck_investment_installments_paid_non_negative'),
    sa.CheckConstraint('monthly_contribution >= 0', name='ck_investment_monthly_contribution_non_negative'),
    sa.CheckConstraint('total_installments >= 0', name='ck_investment_total_installments_non_negative'),
    sa.CheckConstraint('total_paid >= 0', name='ck_investment_total_paid_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_user_id'), 'investments', ['user_id'], unique=False)
    op.create_index('ix_investments_user_maturity_date', 'investments', ['user_id', 'maturity_date'], unique=False)
    op.create_index('ix_investments_user_next_due', 'investments', ['user_id', 'next_due'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Personal', 'Document', 'Investment', 'Other')", name='ck_reminder_category_valid'),
    sa.CheckConstraint("priority IN ('Low', 'Medium', 'High')", name='ck_reminder_priority_valid'),
    sa.CheckConstraint("source IN ('manual', 'documentExpiry', 'investmentDue')", name='ck_reminder_source_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'linked_entity_type', 'linked_entity_id', name='uq_auto_reminder_source_entity')
    )
    op.create_index('ix_reminders_user_due_at', 'reminders', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('goal_scenario_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation IN ('KEEP_TARGET', 'REDUCE_TARGET', 'EXTEND_DEADLINE', 'INCREASE_CONTRIBUTION', 'DECREASE_CONTRIBUTION', 'PAUSE_CONTRIBUTION')", name='ck_goal_scenario_change_operation_valid'),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['goal_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_scenario_changes_goal_id'), 'goal_scenario_changes', ['goal_id'], unique=False)
    op.create_index('ix_goal_scenario_changes_scenario_id', 'goal_scenario_changes', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_scenario_changes_scenario_id', table_name='goal_scenario_changes')
    op.drop_index(op.f('ix_goal_scenario_changes_goal_id'), table_name='goal_scenario_changes')
    op.drop_table('goal_scenario_changes')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index('ix_reminders_user_due_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_investments_user_next_due', table_name='investments')
    op.drop_index('ix_investments_user_maturity_date', table_name='investments')
    op.drop_index(op.f('ix_investments_user_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index('ix_goal_scenarios_user_id', table_name='goal_scenarios')
    op.drop_table('goal_scenarios')
    op.drop_index('ix_financial_goals_user_id', table_name='financial_goals')
    op.drop_table('financial_goals')
    op.drop_index('ix_expenses_user_transaction_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index('ix_documents_user_expiry_date', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_external_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
